sudo: false
language: node_js
node_js:
  - '10'

cache:
  yarn: true
  directories:
    - ./node_modules

script:
  - yarn lint
  - yarn check
  - yarn test

notifications:
  email:
    on_success: never
    on_failure: always
